<!DOCTYPE html>
<html lang="en">
	<?php Include 'Templates/head.html' ?>
	<body>
		<div class="container">
			
			<?php Include 'Templates/header.html' ?>
			
			<div class="main">
			
				<div class="left">
					
					<div class="content" id = "leftContent">
						
						<h1>First Person Shooter:</h1>
						<?php Include 'Scripts/FPS_Slideshow.html' ?></br>
						<h3>Production time: </h3>
						9 weeks half time</br></br>
						
						<h3>My Contributions:</h3>
							Network - Syncing players and enemies.</br>
							Physics - Adding HAVOK to our custom engine.</br>
							Audio - Adding a wrapper for FMOD with interface for scripting to let the level designers add audio to create a more engaging experience.</br>
						<h3>Engine:</h3>
							In house</br>
						<a href="FPS.php"/>more info</a>
						
						<h1>Real Time Strategy:</h1>
						<?php Include 'Scripts/RTS_Slideshow.html' ?></br>
						<h3>Production time: </h3>
							10 weeks half time</br>
							</br>
						<h3>My Contributions:</h3>
							AI - Using influence maps to alter the enemy players goals to give a player like behaviour.</br>
							Scripting - Adding a Lua interface along with hooks to allow the level designers to script events, features and audio to the game.</br>
							Audio - Adding a wrapper for FMOD with interface for scripting to let the level designers add audio to create a more engaging experience.</br>
							</br>
						<h3>Engine:</h3>
							In house</br>
						<a href="RTS.php"/>more info</a>
						
						<h1>Space Shooter:</h1>
						<?php Include 'Scripts/SS_Slideshow.html' ?></br>
						<h3>Production time: </h3>
							10 weeks half time</br>
							</br>
						<h3>My Contributions:</h3>
							Enemy aiming algorithm - Created an algorithm for the enemy ships to use to calculate the future position of the player depending on their current position and their velocity.</br>
							GUI system - Created a simple system to let the programmers easily create buttons, labels, images, message boxes and the like.</br>
							XML Parsing - Added reading of the XML files generated by our Unity script.</br>
							</br>
						<h3>Engine:</h3>
							In house</br>
						<a href="SpaceShooter.php"/>more info</a>
						
						<h1>Turn Based Strategy:</h1>
						<?php Include 'Scripts/TBS_Slideshow.html' ?></br>
						<h3>Production time: </h3>
							8 weeks half time</br>
							</br>
						<h3>My Contributions:</h3>
							Level editor - a simplistic level editor made in C#.</br>
							Isometric selection algorithm - A simple algorithm to calculate the correct tile to select when using the mouse in game.</br>
							Menus - Using the already implemented GUI system created a basic set of menus.</br>
							</br>
						<h3>Engine:</h3>
							In house</br>
						
						<a href="TBS.php"/>more info</a>
						
					</div>
				
				</div>

				<?php Include 'Templates/right.html' ?>
				
			</div>

			<?php Include 'Templates/footer.php' ?>
			
		</div>
	</body>
</html>
